### PR TITLE
Logout component

### PR DESCRIPTION
**Pull request by wild-kard**
The application was missing the ability for a user to logout from their session from anywhere within the application. 

https://www.loom.com/share/005a2706552c41a9ac3dafe3d66329a5

Description
3/7/22:

[See Trello card here](https://trello.com/c/gJXaEzEW)

Type of change
Bug fix (non-breaking change which fixes an issue)

Change Status
Complete, tested, ready to review and merge

Has This Been Tested
Yes

Checklist

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] I have commented my code, particularly in hard-to-understand areas

- [x] I have made corresponding changes to the documentation

- [x] My changes generate no new warnings

- [ ] There are no merge conflicts

### CODE REVIEW

**Review by ashtilawat23 — APPROVED** [review]

**Comment by ashtilawat23** [comment]
Can you rebase main into your branch? That should resolve the merge conflicts that are there.

**Review by Rex-1031 — APPROVED** [review]
Looks good.

**Review by thecuriousones — APPROVED** [review]
Code looks all good to me!

**Comment by wild-kard** [comment]
> 

Having a lot of issues with this because the filename has changed and there is a rebase conflict. 


Took a few cracks at it but I'm getting stuck.

**Review by gsauce7 — CHANGES_REQUESTED** [review]
This DOES add logout functionality, but shouldn't we also route the end user back to the login page or a public splash page that has a information about the app and a login button?  If we don't, we still have the navbar, even though it requires login to see the protected routes.

**Pull request closed without merging**
