### PR TITLE
Creating template for comps using Ant-D layout

### PR DESCRIPTION
**Pull request by ashtilawat23**
## 3/2/22:

Screen Shot 2022-03-02 at 10 14 18 AM

### What work was done?
- Layout template was turned into 3 stand alone components
- NavHeader and Breadcrumbs were created 
- CSS was made into .less files with basic architecture 
- Added `less-watch-compiler.config.json` to watch and update .less to .css files after running `less-watch-compiler` (must have `less` and `less-watch-compiler` installed globally)

### Why was this work done? 
- The components were made stand alone so they can be used anywhere in the app without Layout
- By separating them, you can also easily fix/locate errors
- With less, we can make css dynamic and expandable, removing redundancy with variable names and other handy functions

### What work was done? 
- Template was created to illustrate file structure for all future components. 
- Template files were created inside the temp dir. 

### Why was this work done? 
- To standardize the creation and styles of all pages inside the application.

### CODE REVIEW

**Review by gsauce7 — COMMENTED** [review]
It's looking good to me, but the only thing is we should have a logout button. I'm currently researching that, along with Collin Falstad.

**Review by stkirk — APPROVED** [review]
I like the standardization of the pages directories

**Review by ShariqAli-Dev — APPROVED** [review]
Everything here seems fine. It will be really helpful to have some kind of template to refer to.

**Review by stkirk — APPROVED** [review]
Like the template and the new standardization of pages file structure

**Pull request merged**
