### PR TITLE
Bugfix/rendering-now-per-page

### PR DESCRIPTION
**Pull request by gsauce7**
What work was done?

3/10/22:

The bug we were getting was a double-render of the Nav Header. This has been fixed.
NavHeader is no longer rendered on index.js. LayoutTemplate page is an example of a page that renders the NavHeader and each new and existing page will follow this example. To be clear, right now there is nothing being rendered at "/" but that will not be a problem going forward because any page will include the NavHeader and we do plan to render the dashboard at "/".

Type of change
    Bugfix
Change Status
    Complete, tested, ready to review by 2 peers and merge
 
Checklist
 [x] My code follows the style guidelines of this project
 [x] I have performed a self-review of my own code
 [ ] My code has been reviewed by at least one peer
 [x] I have commented my code, particularly in hard-to-understand areas
 [x] My changes generate no new warnings
 [ ] I have added tests that prove my fix is effective or that my feature works
 [x] New and existing unit tests pass locally with my changes
 [x] There are no merge conflicts

### CODE REVIEW

**Comment by gsauce7** [comment]
LOOM: https://www.loom.com/share/85017c4b01384b918631b71949666a49

**Review by Rex-1031 — APPROVED** [review]
Good work.

**Review by ShariqAli-Dev — APPROVED** [review]
Perfect! Now we will no longer have the duplicate navbar.

**Comment by wild-kard** [comment]
Good job. Simple fix.

**Pull request merged**
