### PR TITLE
Setup Redux Store

### PR DESCRIPTION
**Pull request by EsdrasBrutus**
# Description

Trello: https://trello.com/c/gZ8v4Zjl/12-feature-redux-setup 

What I did:
I setup a redux store for state management of this project. I redid this pull request to fix the `package-lock.json` issues I was having.

Pair-programmed with Durell Jules
Driver & Navigator

## Type of change

- [x] Feature

## Change Status

- [x] Complete, tested, ready to review and merge

## Has This Been Tested

- [x] Yes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

https://user-images.githubusercontent.com/10622915/150256867-2f1e0e26-c161-4552-9062-9bfd2b94fe5d.mp4

### CODE REVIEW

**Review by ryan-hamblin — CHANGES_REQUESTED** [review]
Overall the redux implementation fits the standard we're looking for which is required from Redux and React applications. Great work! 

There are a few instances where you're missing semi-colons and have some code formatted outside the rules of our formatter/linter. I highly suggest you turn on `formatOnSave` in your VSCode editor so that it'll run the linter and formatter and fix your code upon saving the document. 

You can also run the `ESLint Fix` command which is found in your `package.json` scripts to auto-format prior to commiting.

**Comment by dujules23** [comment]
[Feature/Redux-setup](https://trello.com/c/gZ8v4Zjl/12-feature-redux-setup)

**Review by iam-saeed — DISMISSED** [review]
Good explanation and walkthrough thanks for creating a test component to show that state is rendering from the store - that was a great addition to the video.

**Review by felipe-sq — APPROVED** [review]
Great work with implementing the requested changes on code formatting! The walkthrough video and description were detailed and thorough. I think you may need to rebase main again and push the code through once more since the merge conflict is still showing for the missing HomePage route.

**Review by iam-saeed — APPROVED** [review]
Good explanation and walkthrough thanks for creating a test component to show that state is rendering from the store - that was a great addition to the video.

**Review by felipe-sq — APPROVED** [review]

**Review by slothwithannuzzi — APPROVED** [review]
The code looks solid and the video was very informative. I'm glad you showed an in video test of the code to show that it works as intended.

**Comment by katehunnicutt** [comment]
Really great video and explanation, especially on a topic that's rather complex. Code looks good :)

**Review by ashtilawat23 — APPROVED** [review]

**Pull request merged**
