### PR TITLE
removed homepage secure route that was making github checks fail

### PR DESCRIPTION
**Pull request by EsdrasBrutus**
# Description

What I did: I noticed that the lint checks were failing because of one of the `SecureRoutes` in `index.js` was pointed to a `Homepage` component that was deleted in a previous merged pull request. So I just removed that `SecureRoutes` and now checks should all pass now.

## Type of change

- [x] Bugfix

## Change Status

- [x] Complete, tested, ready to review and merge

## Has This Been Tested

- [x] Yes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by melanie-mendoza — COMMENTED** [review]
That's so weird, I removed this route and the LoadingComponent import on my previous Pull Request. It was merged by Ash last week. Were you able to pull the latest version?

**Comment by EsdrasBrutus** [comment]
I made sure to pull the latest build and the route was there. You can also see on the main branch that it's not passing the checks because of it.

**Review by felipe-sq — APPROVED** [review]
Great catch! I've noticed that some files have changed/updated on some previous PRs, even when we don't seem to be manually doing so ourselves. I do remember seeing this error relating to the LoadingComponent route.

**Review by ashtilawat23 — APPROVED** [review]
Amazing!!

**Pull request merged**
