### PR TITLE
Case Services Page wireframe designs for mobile, tablet and desktop.

### PR DESCRIPTION
**Pull request by felipe-sq**
# Description

Trello: N/A

## What I did:
I created wireframe designs for the Case Services page. Wireframes were created for desktop, tablet and mobile. These are stored in the assets folder, under a UX Design folder specifically for wireframes. There is a readme file named *Services Wireframes* which has links to the design images and the images are also stored in the same folder for easy access. 

## Type of change

- [x] Feature/UX Design

## Change Status

- [x] Complete, tested, ready to review and merge

## Has This Been Tested

- [x] N/A

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

## Screenshots/Images

Mobile - Services WF

Tablet - Services WF

Desktop - Services WF

https://www.loom.com/share/fe3283169f174a7da73ddc50d90cebc2

### CODE REVIEW

**Review by ashtilawat23 — CHANGES_REQUESTED** [review]
Can you rebase main one last time before I merge this? Thanks!

**Comment by felipe-sq** [comment]
> Can you rebase main one last time before I merge this? Thanks!

@ashtilawat23 Done! I was getting an error on my local terminal console, but it appears that everything looks good after I rebased main.

**Review by slothwithannuzzi — APPROVED** [review]
Fantastic Job Felipe! The wireframes look great! The loom video is very helpful in showing us how everything is organized.

**Review by iam-saeed — APPROVED** [review]
Awesome job Felipe! I love the way the wireframes look, thanks for the detailed overview!

**Review by ashtilawat23 — APPROVED** [review]

**Pull request merged**
