### PR TITLE
Feature/fe case details case view

### PR DESCRIPTION
**Pull request by Mad-Mal**
Why?
The stakeholder identified the importance of viewing and editing case details per case.

What work was done?
The CaseDetails page was built with the clients name and all info regarding that case. The stakeholder asked for collapsible  accordion panels for all of the information and editable forms to be placed in. The forms are currently not built but when they are they can be imported and added to these collapsible panels. We also incorporated buttons that interact with these forms, such as printing out documents, once the forms have been created and are added these buttons can be made functional. The stakeholder also asked for all of the case notes to be added with the ability to filter by keyword as well as add new notes to the case. The stakeholder asked for all previous case notes to be in a scrollable window so the page would not extend to far down, this functionality has been added. 

Loom video: https://www.loom.com/share/80c56860efcc4d86ba6c23d175bdb519
Trello card: https://trello.com/c/BgWXWOef/70-build-out-case-details-on-the-fe-for-the-case-view

### CODE REVIEW

**Review by MinaMonsi — DISMISSED** [review]
Great work, Mallory! I appreciated the comments you wrote to further identify or explain your code.

**Review by Valeriusdev — APPROVED** [review]
Mallory, you did a great job. I like that you've built the webpage according to the Figma design.

**Review by ashtilawat23 — CHANGES_REQUESTED** [review]
Let's remove the package.json and package-lock.json from this PR. 
Here's how you should go about doing that:
1. In your root directory on the same branch as your PR, run `git checkout package.json`.
2. After that, run `git checkout package-lock.json`.
3. Then you can stage the new files and commit it to this PR.

**Review by ashtilawat23 — APPROVED** [review]
Conflicts resolved.

**Review by Valeriusdev — APPROVED** [review]
Well done.

**Pull request merged**
