### PR TITLE
Created wireframe design for Single Case View page (mobile/tablet/desktop)

### PR DESCRIPTION
**Pull request by felipe-sq**
# Description

Trello (not completing the entire card; only working on Single Case View wireframe designs on this PR): https://trello.com/c/9HBM8OXX/1-as-a-case-manager-i-want-a-mobile-tablet-first-design-so-that-i-can-work-my-cases-from-a-tablet-laptop-or-mobile

## What I did:
I created wireframe designs for the Single Case View page. Wireframes were created for desktop, tablet and mobile. These are stored in the assets folder, under a UX Design folder specifically for wireframes (housed in its own Single Case View folder). There is a readme file named *Single Case View Wireframes* which has links to the design images, and the images are also stored in the same folder for easy access. 

## Type of change

- [x] Feature/UX Design

## Change Status

- [x] Complete, tested, ready to review and merge

## Has This Been Tested

- [x] N/A

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

## Screenshots/Images (updated)

Single Case View - Mobile
Single Case View - Tablet
Single Case View - Desktop

### CODE REVIEW

**Comment by felipe-sq** [comment]
> These are looking good! Here are some thoughts:
> 
> 1. We may want to move the intake page next to the dashboard for ease for the end user
> 2. a filter option needs to be added to the dashboard to be able quickly find a case
> 3. filter option for the notes portion as well
> 4. for future functionality what happens when you click all cases? Does a modal pop up or does it navigate to a new page?
> 5. there should be a profile picture to let the user know this is there specific dashboard
> 6. where would the log out button go?
> 7. thoughts about a notification button? Could be helpful depending on the functionality

Super great thoughts! Thank you @cyreallen! I've updated the wireframes to include a profile picture on the tablet and desktop (mirroring Amber's Dashboard wireframes). Also updated with the filter option for notes. I'm thinking the logout button might go on the profile page to keep from taking up screen real estate with extra buttons, but a logout button can also be added next to the profile picture if needed. For all cases, I'm thinking the link will navigate to a new page, but I'm not sure that has been discussed/planned out yet. I'll push the updated wireframes shortly.

**Review by EsdrasBrutus — APPROVED** [review]
I really like the design! It looks easy to read and traverse through. nice work

**Review by jake-linn — APPROVED** [review]
Looking good! I like how the dashboard buttons are at the bottom of the screen for the phone version while at the top for the tablet version. Make the navigation feel more fluid.

**Review by slothwithannuzzi — APPROVED** [review]
Great job wit these! It's a simple and effective design that is perfect for this project.

**Review by jdeltoro88 — COMMENTED** [review]
clean design easy to navigate

**Pull request merged**
