### PR TITLE
Cleaned up the repo by removing unnecessary components

### PR DESCRIPTION
**Pull request by melanie-mendoza**
The starter repo had components and code that were not needed for the design and scope of this project.

What work was done?
-    I deleted the Home and Landing components and files inside /pages.

### CODE REVIEW

**Review by dujules23 — APPROVED** [review]
Good job removing the unnecessary code. This will help us create meaningful code and make sure things are clean. Thanks!

**Review by ashtilawat23 — CHANGES_REQUESTED** [review]
Looks like you deleted the entire package-lock file?

**Review by EsdrasBrutus — APPROVED** [review]
looks good, but like Ash has pointed out you seem to have deleted the `package-lock.json`.

**Comment by melanie-mendoza** [comment]
> Looks like you deleted the entire package-lock file?



> Looks like you deleted the entire package-lock file?

Thanks for catching that. I had a question about this, actually, and was meaning to ask you when we go back to regular class hours. It's weird why this shows up in the Files Changed. If you look at my local version of the repo, package-lock.json is still there. I did not touch this file whatsoever when I deleted Home and Landing. Any ideas why this happened?

**Pull request closed without merging**
