### PR TITLE
Feature/Sidebar menu of Calendar page

### PR DESCRIPTION
**Pull request by Valeriusdev**
**Why?**
The stakeholder mentioned on one of our meetings that he wants the application to have Calendar page. Users should be able to see the upcoming meetings and create new events on their Calendar pages. I created Calendar page according to the application structure. Also, I was assigned to create Sidebar component of the page.

**What work was done?**
I created Calendar page and Sidebar component of Calendar page.

**Loom video:** https://www.loom.com/share/d0e2f8eb94cd4edca9eb13b3043420a9 

**Trello card:** https://trello.com/c/6MNUnyNY/19-as-a-case-manager-i-want-a-calendar-with-a-week-view-so-that-i-can-see-my-weekly-activities

### CODE REVIEW

**Review by Mad-Mal — APPROVED** [review]
Great job Val! Your code is very clean and easy to read! Great Loom video as well!

**Review by masterasia1 — DISMISSED** [review]
Awesome job! Your code is clear and the sidebar looks great. Good work on the Loom video as well.

**Comment by MinaMonsi** [comment]
Great work, Val! I love how you coded the side bar to reflect the stakeholder's wishes.  It looks exactly like the figma design that we worked on.

**Review by MinaMonsi — DISMISSED** [review]

**Review by SJMucho — APPROVED** [review]
Yes I concur!

**Pull request merged**
